/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_catch22_chainsaw_GameActivity */

#ifndef _Included_com_catch22_chainsaw_GameActivity
#define _Included_com_catch22_chainsaw_GameActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_catch22_chainsaw_GameActivity
 * Method:    createGLRenderer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_catch22_chainsaw_GameActivity_createGLRenderer(JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
